# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Starting Build!
  displayName: 'Go! Run a one-line script'
  
task: PublishPipelineArtifact@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/ci1.txt'
    artifactName: 'text file'
    
task: PublishPipelineArtifact@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/ci2.txt'
    artifactName: 'second text file'
    
- script: |
    echo Build Finished!
  displayName: 'Done! Run a one-line script'
